// Generated by LiveScript 1.4.0
(function(){
  var backbone, A, B, C, c;
  backbone = require('./index');
  A = exports.A = backbone.Model.extend4000({
    _name: 'A1',
    initialize: function(it){
      return console.log('initargs', it);
    },
    testf: function(){
      return console.log('testf a1');
    }
  }, {
    _name: 'A2',
    initialize: function(){
      return console.log('getbla', this.bla);
    },
    testf: function(){
      return console.log('testf a2');
    }
  });
  B = exports.B = A.extend4000({
    _name: 'B',
    initialize: function(){
      return console.log("VALIDATOR", this.bla, this.get('bla'));
    },
    testf: function(){
      console.log('testf b called');
      this._super('testf', 1, 2);
      return 3;
    }
  });
  C = exports.C = B.extend4000({
    _name: 'C',
    bla: 6
  });
  c = new C({
    bla: 666
  });
  console.log(c.testf());
}).call(this);
